### ISSUE TITLE
in add-to-mip, need to reject relative paths or convert to full path

### ISSUE THREAD

**Issue by alaniwi** [cedadev/ceda-mip-tools#6]
add-to-mip accepts relative paths but these do not work in the publication system

**Comment by alaniwi** [comment]
Added commit that is only partially tested so far (tested the lines of code interactively, but haven't tried running add-to-mip with it in).

**Comment by alaniwi** [comment]
Using normpath rather than realpath here, because if the user has put symlinks then provided that the path as presented contains the correct DRS structure needed to work out the dataset ID, we don't mind if the directories are symlinked to somewhere else that might not have that structure.

**Comment by alaniwi** [comment]
Now all fully tested including submitting to CREPP (test instance) and running chain in ceda-test as far as PopulateFilesController. Tagged and deployed.

**Comment by jonnyhtw** [comment]
Awesome, thanks @alaniwi
